spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/web?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 1q2w3e4r
    driver-class: com.mysql.jdbc.Driver